Add CI logic to build release artifacts
Signed-off-by: Andy Doan <andy@foundries.io>

diff --git a/.jobserv.yml b/.jobserv.yml
--- a/.jobserv.yml
+++ b/.jobserv.yml
@@ -8,8 +8,41 @@ triggers:
         host-tag: amd64
         script: unit-test
 
+  - name: create-release
+    type: git_poller
+    params:
+      GIT_URL: "https://github.com/doanac/fioctl.git"
+      GIT_POLL_REFS: "refs/tags/*"
+    runs:
+      - name: create-binaries
+        container: golang:1.13
+        host-tag: amd64
+        script: create-binaries
+
 scripts:
 
   unit-test: |
     #!/bin/sh -ex
     make check
+
+  create-binaries: |
+    #!/bin/sh -e
+    make
+
+    GH_REPO="https://api.github.com/repos/foundriesio/fioctl"
+    GH_TAGS="$GH_REPO/releases/tags/$tag"
+    AUTH="Authorization: token $(cat /secrets/githubtok)"
+
+    # Validate token.
+    curl -o /dev/null -sH "$AUTH" $GH_REPO || { echo "Error: Invalid repo, token or network issue!";  exit 1; }
+
+    response=$(curl -sH "$AUTH" $GH_TAGS)
+    eval $(echo "$response" | grep -m 1 "id.:" | grep -w id | tr : = | tr -cd '[[:alnum:]]=')
+    [ "$id" ] || { echo "Error: Failed to get release id for tag: $tag"; echo "$response" | awk 'length($0)<100' >&2; exit 1; }
+
+    cd bin
+    for filename in `ls`; do
+      echo "Uploading $filename ..."
+      GH_ASSET="https://uploads.github.com/repos/foundriesio/fioctl/releases/$id/assets?name=$filename)"
+      curl --data-binary @"$filename" -H "$AUTH" -H "Content-Type: application/octet-stream" $GH_ASSET
+    done
